server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://3.37.5.79:3306/date_test?useUnicode=true&characterEncoding=utf8&autoReconnetion=true
    username: root
    password: cubox2021!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 4
  jpa:
    show-sql: true
    database: mysql
    hibernate:
        ddl-auto: validate
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true