spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: cubox2020!
  basic:
    enabled: false