spring:
  profiles:
    active: local
    devtools:
      add-properties: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect